//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CJB_Medical.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Trwa generowanie kontraktu komunikatu, ponieważ nazwa elementu GetGenderResult z przestrzeni nazw http://tempuri.org/ nie ma atrybutu nillable.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGender", ReplyAction="*")]
        CJB_Medical.ServiceReference.GetGenderResponse GetGender(CJB_Medical.ServiceReference.GetGenderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGender", ReplyAction="*")]
        System.Threading.Tasks.Task<CJB_Medical.ServiceReference.GetGenderResponse> GetGenderAsync(CJB_Medical.ServiceReference.GetGenderRequest request);
        
        // CODEGEN: Trwa generowanie kontraktu komunikatu, ponieważ nazwa elementu serializedUser z przestrzeni nazw http://tempuri.org/ nie ma atrybutu nillable.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddUser", ReplyAction="*")]
        CJB_Medical.ServiceReference.AddUserResponse AddUser(CJB_Medical.ServiceReference.AddUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddUser", ReplyAction="*")]
        System.Threading.Tasks.Task<CJB_Medical.ServiceReference.AddUserResponse> AddUserAsync(CJB_Medical.ServiceReference.AddUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGenderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGender", Namespace="http://tempuri.org/", Order=0)]
        public CJB_Medical.ServiceReference.GetGenderRequestBody Body;
        
        public GetGenderRequest() {
        }
        
        public GetGenderRequest(CJB_Medical.ServiceReference.GetGenderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetGenderRequestBody {
        
        public GetGenderRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGenderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGenderResponse", Namespace="http://tempuri.org/", Order=0)]
        public CJB_Medical.ServiceReference.GetGenderResponseBody Body;
        
        public GetGenderResponse() {
        }
        
        public GetGenderResponse(CJB_Medical.ServiceReference.GetGenderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGenderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetGenderResult;
        
        public GetGenderResponseBody() {
        }
        
        public GetGenderResponseBody(string GetGenderResult) {
            this.GetGenderResult = GetGenderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUser", Namespace="http://tempuri.org/", Order=0)]
        public CJB_Medical.ServiceReference.AddUserRequestBody Body;
        
        public AddUserRequest() {
        }
        
        public AddUserRequest(CJB_Medical.ServiceReference.AddUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string serializedUser;
        
        public AddUserRequestBody() {
        }
        
        public AddUserRequestBody(string serializedUser) {
            this.serializedUser = serializedUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public CJB_Medical.ServiceReference.AddUserResponseBody Body;
        
        public AddUserResponse() {
        }
        
        public AddUserResponse(CJB_Medical.ServiceReference.AddUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddUserResponseBody {
        
        public AddUserResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : CJB_Medical.ServiceReference.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<CJB_Medical.ServiceReference.WebServiceSoap>, CJB_Medical.ServiceReference.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CJB_Medical.ServiceReference.GetGenderResponse CJB_Medical.ServiceReference.WebServiceSoap.GetGender(CJB_Medical.ServiceReference.GetGenderRequest request) {
            return base.Channel.GetGender(request);
        }
        
        public string GetGender() {
            CJB_Medical.ServiceReference.GetGenderRequest inValue = new CJB_Medical.ServiceReference.GetGenderRequest();
            inValue.Body = new CJB_Medical.ServiceReference.GetGenderRequestBody();
            CJB_Medical.ServiceReference.GetGenderResponse retVal = ((CJB_Medical.ServiceReference.WebServiceSoap)(this)).GetGender(inValue);
            return retVal.Body.GetGenderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CJB_Medical.ServiceReference.GetGenderResponse> CJB_Medical.ServiceReference.WebServiceSoap.GetGenderAsync(CJB_Medical.ServiceReference.GetGenderRequest request) {
            return base.Channel.GetGenderAsync(request);
        }
        
        public System.Threading.Tasks.Task<CJB_Medical.ServiceReference.GetGenderResponse> GetGenderAsync() {
            CJB_Medical.ServiceReference.GetGenderRequest inValue = new CJB_Medical.ServiceReference.GetGenderRequest();
            inValue.Body = new CJB_Medical.ServiceReference.GetGenderRequestBody();
            return ((CJB_Medical.ServiceReference.WebServiceSoap)(this)).GetGenderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CJB_Medical.ServiceReference.AddUserResponse CJB_Medical.ServiceReference.WebServiceSoap.AddUser(CJB_Medical.ServiceReference.AddUserRequest request) {
            return base.Channel.AddUser(request);
        }
        
        public void AddUser(string serializedUser) {
            CJB_Medical.ServiceReference.AddUserRequest inValue = new CJB_Medical.ServiceReference.AddUserRequest();
            inValue.Body = new CJB_Medical.ServiceReference.AddUserRequestBody();
            inValue.Body.serializedUser = serializedUser;
            CJB_Medical.ServiceReference.AddUserResponse retVal = ((CJB_Medical.ServiceReference.WebServiceSoap)(this)).AddUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CJB_Medical.ServiceReference.AddUserResponse> CJB_Medical.ServiceReference.WebServiceSoap.AddUserAsync(CJB_Medical.ServiceReference.AddUserRequest request) {
            return base.Channel.AddUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<CJB_Medical.ServiceReference.AddUserResponse> AddUserAsync(string serializedUser) {
            CJB_Medical.ServiceReference.AddUserRequest inValue = new CJB_Medical.ServiceReference.AddUserRequest();
            inValue.Body = new CJB_Medical.ServiceReference.AddUserRequestBody();
            inValue.Body.serializedUser = serializedUser;
            return ((CJB_Medical.ServiceReference.WebServiceSoap)(this)).AddUserAsync(inValue);
        }
    }
}
